import { img1, img2, img3 } from "./images";
import { Istate } from "./types";

export const jsonData:Istate['data'][]= [
  {
    id: 1,
    img: img3,
    Name: "3 BHK Flats for rent",
    Address: "in Indis PBEL City, Appa Junction",
    Date: "JUL 27, 2023",
    Time: "At 09:00 PM",
    Payment: "Cash",
    Amount: "₹89 Lac",
    active: false,
    Status: "Sold",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
  {
    id: 2,
    img: img1,
    Name: "4 Bedroom House...",
    Address: "in Nallaganda, Hyderabad",
    Date: "JUL 25, 2023",
    Time: "At 05:00 PM",
    Payment: "Check",
    Amount: "₹60 Lac",
    active: false,
    Status: "Sold",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
  {
    id: 3,
    img: img2,
    Name: "3 Bedroom House...",
    Address: "North Carolina, USA",
    Date: "JUL 22, 2023",
    Time: "At 08:00 AM",
    Payment: "Cash",
    Amount: "₹40 K",
    active: false,

    Status: "Pending",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
  {
    id: 4,
    img: img3,
    Name: "Sunflower Suits",
    Address: "StarCo Avenue, UK",
    Date: "JUL 19, 2023",
    Time: "At 11:00 PM",
    Payment: "Cash",
    Amount: "₹10 K",
    active: false,
    Status: "Rejected",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
  {
    id: 5,
    img: img1,
    Name: "The Stars Hotels",
    Address: "North Carolina, USA",
    Date: "JUL 15, 2023",
    Time: "At 07:00 PM",
    active: false,

    Payment: "Cash",
    Amount: "₹78 Lac",
    Status: "Sold",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
  {
    id: 6,
    img: img2,
    Name: "Sunflower Suits",
    Address: "StarCo Avenue, UK",
    Date: "JUL 15, 2023",
    Time: "At 05:00 PM",
    active: false,

    Payment: "Check",
    Amount: "₹20 K",
    Status: "Rented",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
  {
    id: 7,
    img: img3,
    Name: "Co Apartment",
    Address: "StarCo Avenue, UK",
    Date: "JUL 14, 2023",
    Time: "At 09:00 AM",
    Payment: "Check",
    Amount: "₹3 Cr",
    active: false,

    Status: "Sold",
    Actions: { Edit: "Edit", Delete: "Delete" },
  },
];
