export const Styles = {
  gridContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  gridItem: {
    display: "flex",
  },
  menuContainer: {
    display: { xs: "flex", sm: "flex" },
    width: "100%",
    justifyContent: { xs: "space-between", sm: "start" },
    alignItems: { xs: "start", sm: "center" },
    cursor: "pointer",
    position: "relative",
  },
  dateContainer: {
    display: { xs: "flex", sm: "none" },
  },
  date: {
    fontSize: { xs: "16px" },
    fontWeight: "600",
    color: "#163762",
  },
  name: {
    fontSize: { xs: "16px" },
    fontWeight: "500",
    marginRight: "5px",
  },
  soldText: {
    color: "#163762",
  },
  pendingText: {
    color: "#829BB0",
  },
  rejectedText: {
    color: "#EC6C69",
  },
  rentedText: {
    color: "#163762",
  },
  address: {
    color: "#163762",
    fontSize: { xs: "12px", sm: "12px", md: "12px" },
    fontWeight: "400",
    marginRight: "5px",
  },
  time: {
    color: "#163762",
    fontSize: { xs: "12px", sm: "12px", md: "12px" },
    fontWeight: "400",
    marginRight: "5px",
    alignSelf: { xs: "end", sm: "start" },
  },
  modalContainer: {
    position: "absolute" as "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 400,
    bgcolor: "background.paper",
    border: "2px solid #000",
    boxShadow: 24,
    p: 4,
  },
  editContainer: {
    display: "flex",
    flexDirection: "column",
    padding: "20px 10px",
    justifyContent: "center",
    gap: 2,
    width: "130px",
    position: "absolute",
    top: 30,
    left: -1,
    zIndex: 900,
  },
  bigImgContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "15px",
    height: { xs: "60px" },
    width: { xs: "60px" },
    aspectRatio: "1/1",
    position: "relative",
    cursor: "pointer",
  },
  img: {
    width: "100%",
    height: "100%",
    borderRadius: "15px",
    objectFit: "inherite",
    transition: "1s ease all",
  },
  gridItemContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "15px 0px",
    borderTop: { xs: "3px solid #8c8c8833", sm: "1px solid #8c8c8833" },
  },
  statusBtn: {
    color: "#fff",
    display: { xs: "flex", sm: "flex" },
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: { xs: "16px" },
    borderRadius: "10px",
    width: "100px",
    height: "40px",
    fontWeight: "400",
    lineHeight: "20px",
    letterSpacing: "0.1px",
    cursor: "pointer",
    textTransform: "none",
    "&:hover": {
      color: "#5c52ba",
    },
  },
  soldBtn: {
    backgroundColor: { xs: "#fff", sm: "#163762" },
    color: { xs: "#163762", sm: "#fff" },
    "&:hover": {
      backgroundColor: { xs: "#fff", sm: "#163762" },
    },
  },
  pendingBtn: {
    backgroundColor: { xs: "#fff", sm: "#829BB0" },
    color: { xs: "#829BB0", sm: "#fff" },
    "&:hover": {
      backgroundColor: { xs: "#fff", sm: "#829BB0" },
    },
  },
  rejectedBtn: {
    backgroundColor: { xs: "#fff", sm: "#EC6C69" },
    color: { xs: "#EC6C69", sm: "#fff" },
    "&:hover": {
      backgroundColor: { xs: "#fff", sm: "#EC6C69" },
    },
  },
  rentedBtn: {
    backgroundColor: { xs: "#fff", sm: "#3879BF" },
    color: { xs: "#3879BF", sm: "#fff" },
    "&:hover": {
      backgroundColor: { xs: "#fff", sm: "#3879BF" },
    },
  },
  moreBtn: {
    backgroundColor: "#fff",
    color: "#163762",
    display: { xs: "none", sm: "flex" },
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: { xs: "16px" },
    borderRadius: "10px",
    width: "100px",
    height: "40px",
    border: "1px solid #dbdbdb",
    fontWeight: "600",
    lineHeight: "20px",
    letterSpacing: "0.1px",
    cursor: "pointer",
    textTransform: "none",
    "&:hover": {
      color: "#163762",
      backgroundColor: "#fff",
    },
  },
};
