export const styles = {
  mainContainer: {
    width: "100%",
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    backgroundColor: "#fff",
    bakgroundSize: "cover",
    position: "sticky",
    top: "0px",
    zIndex: 9,
  },
  moreBtn: {
    backgroundColor: "#163762",
    color: "#fff",
    display: { xs: "flex", sm: "flex" },
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: { xs: "16px" },
    borderRadius: "10px",
    width: "100px",
    height: "40px",
    border: "1px solid #dbdbdb",
    fontWeight: "600",
    lineHeight: "20px",
    letterSpacing: "0.1px",
    cursor: "pointer",
    textTransform: "none",
    "&:hover": {
      color: "#fff",
      backgroundColor: "#163762",
    },
  },
  addButtonContainer: {
    diplay: "flex",
    alignSelf: "end",
  },
  addButtonContainer2: {
    display: { xs: "flex", sm: "none" },
    alignSelf: "end",
  },
  mainInnerContainer: {
    width: "100%",
    flexDirection: "column",
    display: { xs: "none", sm: "flex" },
    alignItems: "center",
    backgroundColor: "#fff",
  },
  modalContainer: {
    position: "absolute" as "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: 300, sm: 450 },
    height: 300,
    bgcolor: "background.paper",
    border: "2px solid #000",
    boxShadow: 24,
    overflow: "scroll",
    p: 5,
    paddingTop: "20em",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 2,
  },
  helperText: {
    color: "#00030C",
    lineHeight: "24px",
    fontWeight: 600,
    fontSize: "16px",
    fontFamily: "'Poppins', sans-serif",
    margin: 0,
  },
  statusBtn: {
    color: "#fff",
    display: { xs: "flex", sm: "flex" },
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: { xs: "16px" },
    borderRadius: "10px",
    width: "100px",
    height: "40px",
    fontWeight: "400",
    lineHeight: "20px",
    letterSpacing: "0.1px",
    cursor: "pointer",
    textTransform: "none",
    "&:hover": {
      color: "#5c52ba",
    },
  },
  cancelBtn: {
    color: "#163762",
    border: "1px solid #163762",
  },
  soldBtn: {
    backgroundColor: { xs: "#fff", sm: "#163762" },
    color: { xs: "#163762", sm: "#fff" },
    "&:hover": {
      backgroundColor: { xs: "#fff", sm: "#163762" },
    },
  },
  select: {
    margin: 0,
    "& legend": { display: "none" },

    "& .MuiInputLabel-shrink": { opacity: 0, transition: "all 0.2s ease-in" },
  },
  usernameInput: {
    "& input::-webkit-outer-spin-button": {
      WebkitAppearance: "none",
    },
    "& input::-webkit-inner-spin-button": {
      WebkitAppearance: "none",
    },

    backgroundColor: "transparent",
    "& fieldset.MuiOutlinedInput-notchedOutline": {
      borderRadius: "10px",
      backgroundColor: "none",
    },
    width: "100%",
  },
  passwordInput: {
    "& input::-webkit-outer-spin-button": {
      WebkitAppearance: "none",
    },
    "& input::-webkit-inner-spin-button": {
      WebkitAppearance: "none",
    },
    "& fieldset.MuiOutlinedInput-notchedOutline": {
      borderRadius: "10px",
      backgroundColor: "none",
      width: "100%",
    },
  },
  inputLabel: {
    border: "1px dashed grey",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "18px",
    cursor: "pointer",
    height: "120px",
    width: "210px",
  },
  avatarContainer: {
    position: "relative",
    display: "flex",
  },
  err: {
    color: "#b00020",
  },
  bigImageContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    aspectRatio: "1/1",
    borderRadius: "18px",
    height: "120px",
    width: "210px",
    cursor: "pointer",
  },
  avatar: {
    width: "100%",
    height: "100%",
    objectFit: "inherite",
    transition: "1s ease all",
  },
  imageIcon: {
    fontSize: "40px",
  },
  drop: {
    fontSize: "15px",
    textAlign: "center",
  },
  click: {
    color: "#163762",
    fontWeight: "600",
    cursor: "pointer",
  },
  imageContainer: {
    borderRadius: "8px",
    border: "2px solid #8fbce9",
    width: "100%",
    padding: "8px 12px",
  },
  toolbar: {
    position: "sticky",
    top: 0,
    backgroundColor: "#fff",
    padding: { xs: "8px 0px", sm: "20px 0px" },
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    zIndex: 99999,
    borderBottom: "1px solid #8c8c8833",
  },
  toolbarInnerContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  icon: {
    color: "#fff",
  },
  homeContainer2: {
    display: { xs: "flex", sm: "none" },
    justifyContent: { xs: "space-evenly" },
    gap: 1,
  },
  gridContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  gridItem: {
    display: "flex",
  },
  menuContainer: {
    display: { xs: "flex", sm: "flex" },
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
  importIcon: {
    color: "#163762",
  },
  name: {
    color: "#163762",
    fontSize: { xs: "16px", sm: "16px", md: "16px" },
    fontWeight: "600",
    marginRight: "5px",
  },
};
